# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import files_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilePathModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FilesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=files_app.models.MyFileStorage(), upload_to=files_app.models.upload_path)),
                ('path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_app.FilePathModel')),
            ],
        ),
    ]
