# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesmodel',
            name='description',
            field=models.TextField(default='description', max_length=1024),
        ),
    ]
