# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0002_filesmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesmodel',
            name='description',
            field=models.CharField(default='description', max_length=128),
        ),
    ]
